[PRIMA-9846]: Nuovo alert Datadog in caso di errore su consumo messaggi RabbitMQ
primait/amqpx pull request #94
Opened 2021-10-04 08:24 UTC by edoardocostantinidev

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-9846

This PR includes:

- Small fix to change the return type of `handle_message_rejection` callback from `{:ok}` to `:ok`
- `handle_message_rejection` now also has the rejected message as input for better observability

2021-10-04 08:26 UTC, mbusi submitted a review, later dismissed

2021-10-04 08:35 UTC, PaoloLaurenti approved these changes

2021-10-04 12:07 UTC, squaini approved these changes

2021-10-04 21:57 UTC, michelangelomo requested changes
@edoardocostantinidev before merge could you please change the PR title? Also, can you bump amqpx version to a patch inside `mix.exs`? Thank you 😄

2021-10-04 21:59 UTC, edoardocostantinidev commented
> @edoardocostantinidev before merge could you please change the PR title? Also, can you bump amqpx version to a patch inside `mix.exs`? Thank you 😄 

sure thing, I forgot to change the suite-py default. I'll fix it asap

2021-10-05 07:17 UTC, michelangelomo approved these changes

2021-10-05 07:17 UTC, merged